# =================================================================================================
# File: state.py
# Module: Agentic AI Subsystem - Pydantic Workflow State & Telemetry Models
# Student Contributor: Upamada Ekanayake (Group Leader - IT24200314)
# Architecture: AI Layer - Shared durable state schemas and execution telemetry models
# Purpose: Defines the centralized WorkflowState schema for LangGraph nodes, tracking plans,
#          agent execution traces, tool outputs, validation flags, and HITL approval reasons.
# =================================================================================================

from typing import List, Optional, Dict, Any
from pydantic import BaseModel, Field

class AgentStep(BaseModel):
    agent_name: str
    action: str
    status: str  # "SUCCESS", "FAILED", "SKIPPED", "HITL_PAUSED"
    output_summary: str
    execution_time_ms: float

class WorkflowState(BaseModel):
    workflow_id: str
    domain_objective: str
    target_entity_type: str  # "LEASE", "TENANT_APPLICATION", "MAINTENANCE"
    target_entity_id: str
    
    # Execution plan generated by Planning Agent (Upamada)
    plan_steps: List[str] = Field(default_factory=list)
    agent_trace: List[AgentStep] = Field(default_factory=list)
    
    # Input data payload
    tenant_income: Optional[float] = None
    property_rent: Optional[float] = None
    issue_description: Optional[str] = None
    reported_priority: Optional[str] = None
    
    # Tool outputs & enriched evaluations
    screening_score: Optional[int] = None
    rent_to_income_ratio: Optional[float] = None
    identity_verified: Optional[bool] = None
    estimated_cost: Optional[float] = None
    trade_category: Optional[str] = None
    recommended_contractor: Optional[str] = None
    
    # Deterministic Validation & Human-in-the-Loop checkpoint
    validation_passed: bool = False
    requires_human_approval: bool = False
    approval_reason: Optional[str] = None
    final_status: str = "INITIALIZED"  # "PENDING_APPROVAL", "COMPLETED", "FAILED"
