services:
  # 1. ASP.NET Core 10 Web API
  - type: web
    name: rms-backend-api
    runtime: docker
    dockerfilePath: backend/Dockerfile
    dockerContext: backend
    plan: free
    region: singapore
    envVars:
      - key: ASPNETCORE_ENVIRONMENT
        value: Production
      - key: ConnectionStrings__DefaultConnection
        value: Host=ep-bitter-union-azwzwv86-pooler.c-3.ap-southeast-1.aws.neon.tech;Port=5432;Database=neondb;Username=neondb_owner;Password=npg_OGmZB17jWfJh;SSL Mode=Require;Trust Server Certificate=true;
      - key: Jwt__Key
        value: RMS_Super_Secret_Security_Key_SE3090_Assignment_Grading_2026_Key!
      - key: Jwt__Issuer
        value: RMS_API
      - key: Jwt__Audience
        value: RMS_Clients
      - key: AiAgent__BaseUrl
        value: https://rms-ai-orchestrator.onrender.com

  # 2. Internal LangGraph AI Microservice
  - type: web
    name: rms-ai-orchestrator
    runtime: docker
    dockerfilePath: ai-agent/Dockerfile
    dockerContext: ai-agent
    plan: free
    region: singapore
    envVars:
      - key: PORT
        value: 8000
